language: python
python:
    #- "2.6"  # cannot import versioning
    - "2.7"
    - "3.2"
    - "3.3"
    - "3.4"
    - "3.5"
before_install:
    - sudo apt-get -qq update
    - sudo apt-get install -y pylint
    #- sudo apt-get install -y shellcheck
install:
    - pip install -e ./base
    - pip install -e ./git
    - pip install -e ./gitflow
    - pip install -e ./githooks
    - pip install -e ./hooks-demo
    - pip install -e ./pythonic
    - pip install -e ./release
    - pip install -e ./stages
    - pip install -e ./versioning
    - pip install -e ./meta
    #- pip install -U pytest
    #- pip install -U tox
    #- pip install -U tox pytest
script: ./travis_tests.sh
