---

language: python

python:
    # - "2.6"  # cannot import versioning
    - "2.7"
    # - "3.2"  # error in click.utils: u'...
    - "3.3"
    - "3.4"
    - "3.5"

before_install:
    - sudo apt-get -qq update
    - sudo apt-get install -y file
    # - sudo apt-get install -y cabal-install
    # - cabal update
    # - cabal install shellcheck
    - git pull
    - make travis-setup

install:
    - make travis-install

script:
    - make clean

    # the full build and test chain
    # - make travis

    # light version excludes the documentation
    # (this saves ~1:30m on dependency lxml)
    # and the documentation has it's own badge
    - make travis-light

after_success:
    - make travis-success
