language: python
python:
    - "2.7"
    - "3.4"
install:
    - pip install -e base
    #- pip install -U pytest
    #- pip install -U tox
    #- pip install -U tox pytest
script:
    - ft
    - ft self-info
