---

language: python

python:
    # - "2.6"  # cannot import versioning
    - "2.7"
    # - "3.2"  # error in click.utils: u'...
    - "3.3"
    - "3.4"
    - "3.5"

before_install:
    - make travis-setup

install:
    - make travis-install

script:
    - make clean
    - make travis

after_success:
    - make travis-success
