"""
    This file was generated by flowtool-versioning.
    Homepage: https://github.com/isnok/py-flowlib
"""

VERSION_INFO = {'vcs_info': {'commit': 'c7f69a0ae68831c8ee8182d7036efd37956eb15d',
              'dirt': '',
              'latest_tag': 'flowtool-stages-0.7.9',
              'latest_tag_commit': 'c7f69a0ae68831c8ee8182d7036efd37956eb15d',
              'latest_tag_version': '0.7.9',
              'prefix': 'flowtool-stages-',
              'prefix_tag_distances': {'flowtool-stages-0.7.6': 286,
                                       'flowtool-stages-0.7.7': 210,
                                       'flowtool-stages-0.7.8': 133,
                                       'flowtool-stages-0.7.9': 0},
              'tag_version': {'normalized': '0.7.9',
                              'release': (0, 7, 9),
                              'version': '0.7.9'}},
 'version': '0.7.9'}

def get_version():
    global VERSION_INFO
    return VERSION_INFO.get('version', '$Format:%d %H$')
