"""
    This file was generated by flowtool-versioning.
    Homepage: https://github.com/isnok/py-flowlib
"""

VERSION_INFO = {'vcs_info': {'commit': 'ff03a694f683089e559cf923e457a4024a47c17b',
              'dirt': '',
              'latest_tag': 'flowtool-githooks-0.7.31',
              'latest_tag_commit': 'ff03a694f683089e559cf923e457a4024a47c17b',
              'latest_tag_version': '0.7.31',
              'prefix': 'flowtool-githooks-',
              'prefix_tag_distances': {'flowtool-githooks-0.7.28': 122,
                                       'flowtool-githooks-0.7.29': 115,
                                       'flowtool-githooks-0.7.30': 103,
                                       'flowtool-githooks-0.7.31': 0},
              'tag_version': {'normalized': '0.7.31',
                              'release': (0, 7, 31),
                              'version': '0.7.31'}},
 'version': '0.7.31'}

def get_version():
    global VERSION_INFO
    return VERSION_INFO.get('version', '$Format:%d %H$')
