"""
    This file was generated by flowtool-versioning.
    Homepage: https://github.com/isnok/py-flowlib
"""

VERSION_INFO = {'vcs_info': {'commit': '3e4eda0113bf1bea3e8318dd5050edd20fa03de7',
              'dirt': '',
              'latest_tag': 'flowtool-releasing-0.7.16',
              'latest_tag_commit': '3e4eda0113bf1bea3e8318dd5050edd20fa03de7',
              'latest_tag_version': '0.7.16',
              'prefix': 'flowtool-releasing-',
              'prefix_tag_distances': {'flowtool-releasing-0.7.13': 60,
                                       'flowtool-releasing-0.7.14': 14,
                                       'flowtool-releasing-0.7.15': 13,
                                       'flowtool-releasing-0.7.16': 0},
              'tag_version': {'normalized': '0.7.16',
                              'release': (0, 7, 16),
                              'version': '0.7.16'}},
 'version': '0.7.16'}

def get_version():
    global VERSION_INFO
    return VERSION_INFO.get('version', '$Format:%d %H$')
