"""
    This file was generated by flowtool-versioning.
"""

VERSION_INFO = {'tag_version': {'normalized': '0.7.12',
                 'release': (0, 7, 12),
                 'version': '0.7.12'},
 'vcs_info': {'commit': '725a455b0d1395ebd1a9602d5326aed428e3b7c7',
              'dirt': ' M flowtool_python/versioning/cmdclass.py\n',
              'latest_tag': 'flowtool-python-0.7.12',
              'latest_tag_commit': '725a455b0d1395ebd1a9602d5326aed428e3b7c7',
              'latest_tag_version': '0.7.12',
              'prefix': 'flowtool-python-',
              'prefix_tag_distances': {'flowtool-python-0.7.11': 1,
                                       'flowtool-python-0.7.12': 0}},
 'version': '0.7.12.dirty'}

def get_version():
    global VERSION_INFO
    return VERSION_INFO.get('version', 'no_version')
